name: 'Handle Rendering Issue Action'
description: 'Process rendering issues comment with link to new board'
author: 'Bitmark-Inc.'
inputs:
  issue:
    description: 'The issue number to process'
    required: true
  owner:
    description: 'The owner of the incoming repo'
    required: true
  repo:
    description: 'The name of the incoming repo'
    required: true
  label:
    description: 'The name the label for actioning the processing'
    required: true
  GITHUB_TOKEN:
    description: 'The token for incoming repo. Use `secrets.GITHUB_TOKEN` to inject it'
    required: true
  outOwner:
    description: 'The owner of the outgoing repo'
    required: true
  outRepo:
    description: 'The name of the outgoing repo'
    required: true
  OUT_GITHUB_TOKEN:
    description: 'The token to create issue in outgoing repo. Use `secrets.OUT_GITHUB_TOKEN` to inject it'
    required: true
outputs:
  issue:
    description: 'The issue number created by this process'
  owner:
    description: 'The owner of the outgoing repo'
  repo:
    description: 'The name of the outgoing repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --issue
    - ${{ inputs.issue }}
    - --owner
    - ${{ inputs.owner }}
    - --repo
    - ${{ inputs.repo }}
    - --label
    - ${{ inputs.label }}
    - --token
    - ${{ inputs.GITHUB_TOKEN }}
    - --out-owner
    - ${{ inputs.outOwner }}
    - --out-repo
    - ${{ inputs.outRepo }}
    - --out-token
    - ${{ inputs.OUT_GITHUB_TOKEN }}
branding:
  icon: triangle
  color: purple
