name: 'Handle Rendering Issue Action'
description: 'Process rendering issues comment with link to new board'
author: 'Bitmark-Inc.'
inputs:
  issue:
    description: 'The issue number to process'
    required: true
  owner:
    description: 'The owner of the incoming repo'
    required: true
  repo:
    description: 'The name of the incoming repo'
    required: true
  label:
    description: 'The name the label for actioning the processing'
    required: true
  fields:
    description: 'A comma separated set of field to extract (case sensitive)'
    required: true
  closeComment:
    description: 'A message string with a single %s where the URL should be substituted'
    required: false
    default: 'This issue has been moved to a public board: %s'
  token:
    description: 'The token for incoming repo. Use `secrets.GITHUB_TOKEN` to inject it'
    required: true
  outOwner:
    description: 'The owner of the outgoing repo'
    required: true
  outOwnerType:
    description: 'The type [user|organization] of owner owning the project'
    default: 'organization'
    required: false
  outRepo:
    description: 'The name of the outgoing repo'
    required: true
  outProject:
    description: 'The name of the outgoing project'
    required: true
  outToken:
    description: 'The token to create issue in outgoing repo. Use `secrets.OUT_GITHUB_TOKEN` to inject it'
    required: true
outputs:
  issueNumber:
    description: 'The issue number created by this process'
  issueID:
    description: 'The issue ID created by this process'
  owner:
    description: 'The owner of the outgoing repo'
  repo:
    description: 'The name of the outgoing repo'
  project:
    description: 'The name of the project'
  projectID:
    description: 'The ID of the project'
  projectItemID:
    description: 'The ID of the record added to the project'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --verbose
    - --debug
    - --issue
    - ${{ inputs.issue }}
    - --owner
    - ${{ inputs.owner }}
    - --repo
    - ${{ inputs.repo }}
    - --label
    - ${{ inputs.label }}
    - --fields
    - ${{ inputs.fields }}
    - --close-commane
    - ${{ inputs.closeComment }}
    - --token
    - ${{ inputs.token }}
    - --out-owner
    - ${{ inputs.outOwner }}
    - --out-owner-type
    - ${{ inputs.outOwnerType }}
    - --out-repo
    - ${{ inputs.outRepo }}
    - --out-project
    - ${{ inputs.outProject }}
    - --out-token
    - ${{ inputs.outToken }}
branding:
  icon: triangle
  color: purple
